### ISSUE TITLE
&stack = nullptr

### ISSUE THREAD

**Issue by asssh52** [Evdik228/Bad_stack#1]
tries to put error code via unexisting stack address
<img width="262" alt="image" src="https://github.com/user-attachments/assets/292d12dd-3f91-4c9c-a295-9a9170bfa16e">
<img width="359" alt="image" src="https://github.com/user-attachments/assets/bae7344d-81fe-4aeb-802d-8f31c88ac190">
<img width="709" alt="image" src="https://github.com/user-attachments/assets/bd7fdd5e-d97a-462f-881d-7e4b1e64fa59">

**Comment by Evdik228** [comment]
this bug have sicked by ded))

**Comment by Evdik228** [comment]
fixed to!
