### ISSUE TITLE
stack_push while stack was not "ctored"

### ISSUE THREAD

**Issue by asssh52** [Evdik228/Bad_stack#2]
<img width="248" alt="image" src="https://github.com/user-attachments/assets/d9a37bfc-39bd-4661-b649-696d266a4dfc">
<img width="814" alt="image" src="https://github.com/user-attachments/assets/d14097c9-8ac0-4969-b494-06368038e990">
<img width="903" alt="image" src="https://github.com/user-attachments/assets/a0d762c3-1132-4a0a-96a4-a2adf54a3d91">
verification passes uncreated stack to other funcs:
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/615df98b-90fc-4749-9ac7-554905a962bb">

**Comment by Evdik228** [comment]
quick fixed)) thank`s bro!
