### ISSUE TITLE
Stack_ctor(nullptr) crashes program

### ISSUE THREAD

**Issue by asssh52** [Evdik228/Bad_stack#3]
<img width="299" alt="image" src="https://github.com/user-attachments/assets/a0e81fed-1e84-4679-9c87-6682d7031e66">
<img width="234" alt="image" src="https://github.com/user-attachments/assets/7eb50ab2-5417-4b05-8fe4-eccc5ceecbf2">
<img width="754" alt="image" src="https://github.com/user-attachments/assets/22e17fe1-8784-4b14-885f-6c5acffff4eb">
no checks whether inputted stack address is null

**Comment by Evdik228** [comment]
it`s an error that, you should sicked too
