### ISSUE TITLE
undefined behaviour while poping an element when stk->size = 0

### ISSUE THREAD

**Issue by asssh52** [Evdik228/Bad_stack#5]
<img width="467" alt="image" src="https://github.com/user-attachments/assets/26906f4b-d369-4f6a-adb6-921d435c9543">
<img width="398" alt="image" src="https://github.com/user-attachments/assets/7aba54bc-b432-437f-87a7-93c3dba670c1">
<img width="803" alt="image" src="https://github.com/user-attachments/assets/173aa078-1ca4-41ef-b80d-74b9531dc9d5">
stack_pop does not stop when size == 0

**Comment by Evdik228** [comment]
it was error, which you should sicked

**Comment by Evdik228** [comment]
alredy fixed
