### ISSUE TITLE
stack_dtor("empty stack") => segmentation fault

### ISSUE THREAD

**Issue by asssh52** [Evdik228/Bad_stack#6]
<img width="314" alt="image" src="https://github.com/user-attachments/assets/10da8254-5a8a-4431-a317-09337c8fd3d9">
<img width="489" alt="image" src="https://github.com/user-attachments/assets/bf6d5f31-a018-43e3-a736-d91d07f6761f">
<img width="630" alt="image" src="https://github.com/user-attachments/assets/2b503475-9bc3-4e61-9bbe-fd707de8b837">
stack pointer != nullptr and program goes on and tries to free unallocated address

**Comment by Evdik228** [comment]
issue fixed! thanks a lot
